[package]
name = "packwiz_modlist"
description = "Creates a modlist from packwiz"
authors = ["Ricky12Awesome"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
categories = ["command-line-utilities"]
repository = "https://github.com/Ricky12Awesome/packwiz_modlist"
homepage = "https://github.com/Ricky12Awesome/packwiz_modlist"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "^0.11", features = ["json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
clap = { version = "^3.1", features = ["cargo", "derive"] }
toml = "^0.5"
tokio = { version = "^1.17", features = ["full"] }
anyhow = "^1.0"
thiserror = "^1.0"
color-eyre = "^0.5"
log = "^0.4"
simple_logger = { version = "^2.1", default-features = false, features = ["colored"] }
