[package]
name = "packwiz_modlist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "^0.11"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
clap = "^3.1"
toml = "^0.5"
tokio = { version = "^1.17", features = ["full"] }
anyhow = "^1.0"