[package]
name = "packwiz-modlist"
description = "Creates a modlist from packwiz"
authors = ["Ricky12Awesome"]
version = "1.5.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"
keywords = ["packwiz", "modding", "minecraft"]
categories = ["command-line-utilities"]
repository = "https://github.com/Ricky12Awesome/packwiz-modlist"
homepage = "https://github.com/Ricky12Awesome/packwiz-modlist"

[[bin]]
name = "packwizml"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "^0.11", features = ["json"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
clap = { version = "^3.2", features = ["cargo", "derive"] }
toml = "^0.5"
tokio = { version = "^1.19", features = ["full"] }
futures = "^0.3"
thiserror = "^1.0"
colored = "^2.0"
log = "^0.4"
itertools = "^0.10"
simple_logger = { version = "^2.1", default-features = false, features = ["colored"] }

[build-dependencies]
log = "^0.4"
clap = { version = "^3.2", features = ["cargo", "derive"] }
clap_complete = "^3.2"
anyhow = "^1.0"
# So LevelFilter works
simple_logger = { version = "^2.1", default-features = false }