name: Tagged Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

env:
  PROJECT_NAME: packwiz_modlist

jobs:
  artifact:
    name: Artifact for ${{ matrix.job.os-name }}
    runs-on: ${{ matrix.job.os }}

    strategy:
      matrix:
        rust: [ stable ]
        job:
          - os: windows-latest
            os-name: windows
            target: x86_64-pc-windows-msvc
            architecture: x86_64
            binary-postfix: ".exe"
            use-cross: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME }}-${{ matrix.job.os-name }}-${{ matrix.job.architecture }}
          path: target/release/${{ env.PROJECT_NAME }}-${{ matrix.job.os-name }}-${{ matrix.job.architecture }}${{ matrix.job.binary-postfix }}
          retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: artifact
    if: startsWith(github.ref, 'refs/tags/v') # Ignore this job if I do manual build for testing
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: Release Artifacts
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            */*